### PR TITLE
Allow replacing ~/.virtualgo with VIRTUALGO_ROOT

### LINKED ISSUE #17: Override virtualgoroot (~/.virtualgo)?
We have a project that uses a variety of home-grown shell scripts to provide a similar experience to vg. I'd like to replace it with vg.

One nice feature of our project is that you can check it out anywhere and it will work immediately (as long as you run our shell wrapper, which works well with [direnv](https://direnv.net/)).  We store the equivalent to the `~/.virtualgo/V` directory inside a gitignored directory in the repo itself.  That way you can have multiple checkouts and they just work.

So to port to vg our scripts (we'd still have direnv scripts because we set up non-Go environments as well) would like to be able to just use a fixed environment name and a virtualgoroot that's not global, rather than a global virtualgoroot and a variable environment name.

It looks like we should be able to just define, say, `$VIRTUALGOROOT`, and use it instead of ~/.virtualgo in the shell scripts and utils.Virtualgoroot.  Is that a PR you'd take?

### PR DESCRIPTION
**Pull request by glasser**
Caveat: only tested under bash.  fish code cargo culted from
https://unix.stackexchange.com/questions/81421/how-do-i-reference-a-variable-in-fish-shell-with-a-default-fallback
and untested.

Fixes #17.

### CODE REVIEW

**Comment by JelteF** [comment]
Looks fine, but I'll try to test this in all the shells in the near future. For the moment, could you merge master and regenerate the bindata file?

**Comment by JelteF** [comment]
Just tested it with fish btw and it doesn't work.

**Comment by glasser** [comment]
I updated based on root.

I've finished my evaluation of vg and it looks like it's super great for personal use, but a little overkill for my project's use (where we already need some wrapper scripts in order to support non-Go ecosystems). The part that's most attractive to me is the dep ensure wrapper which adds "write to GOPATH rather than vendor" and "install binaries" to dep — I'm wondering if there's a hope of getting that into upstream dep?  That said I'm still happy to try to finish this PR even though I don't know much about fish.

**Comment by JelteF** [comment]
If you want to install it to test it locally you can probably simply do something like:
```
apt install fish
brew install fish
# or whatever package manager you use
```

probably something like this should work
```
set -l vgr $VIRTUALGO_ROOT
if <check if vgr is empty> 
    set vgr ~/.virtualgo
end
```

zsh and bash worked fine btw.

**Comment by glasser** [comment]
I'm going to have to be honest and say I probably am not going to finish this PR.

**Comment by JelteF** [comment]
Alright, thanks for the info and the start at least. If you leave it open I'll try to fix it myself at some point.

**Comment by JelteF** [comment]
closing this in favor if #42

**Comment by JelteF** [comment]
thanks for the initial work. The only bug actually was that you forgot a `.` in the fish code. Needed this myself now, so fixed that.

**Pull request closed without merging**
